# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dean's blog
email: contact@thomasdurand.fr
description: "Dean's blog is a blog about computer science and development"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thomasdurand.fr" # the base hostname & protocol for your site
twitter_username: deanatoire
github_username: dean151
linkedin_username: thomasdurandverjat

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->